# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\"\x1f\n\x0b\x43lientInput\x12\x10\n\x08\x64\x61taType\x18\x01 \x01(\t\"\x1f\n\x0cServerOutput\x12\x0f\n\x07message\x18\x01 \x01(\t23\n\nServerTest\x12%\n\x04test\x12\x0c.ClientInput\x1a\r.ServerOutput\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTINPUT._serialized_start=16
  _CLIENTINPUT._serialized_end=47
  _SERVEROUTPUT._serialized_start=49
  _SERVEROUTPUT._serialized_end=80
  _SERVERTEST._serialized_start=82
  _SERVERTEST._serialized_end=133
# @@protoc_insertion_point(module_scope)
